### ISSUE TITLE
Error in post() function involving the options parameter

### ISSUE THREAD

**Issue by authyrtyr** [rmccue/Requests#126]
Whenever I call Requets::post() I get the following error:

`PHP Fatal Error: Class 'Requests_Hooks' not found in /web/dev_html/jg/notifii/vendor/rmccue/requests/library/Requests.php on line 484`

It seems to stem from data missing from the `options` parameter. Can someone tell me what that parameter should look like so that it works correctly? There doesn't seem to be a mention of it in the prose documentation (which has examples).

**Comment by michalskop** [comment]
Make sure the webserver has read access to the Requests subdirectory (it was my problem with this error).
