### ISSUE TITLE
Requests halts when requested service is down

### ISSUE THREAD

**Issue by toksea** [rmccue/Requests#141]
Hi!

When I requests a halted service, the whole program halted. I'm using the default options. 

Did I miss something? Or it's designed like this?

Thanks!

**Comment by rmccue** [comment]
Hi!

> When I requests a halted service, the whole program halted. I'm using the default options.

Try turning error reporting on for your server. My guess is that Requests is throwing a `Requests_Exception`, and you're not catching this in your code.

Let me know how that goes.

**Comment by toksea** [comment]
Oh yes it does throw the `Requests_Exception`, I didn't catch that before.

Thank you!
