### ISSUE TITLE
Duplicated line of code?

### ISSUE THREAD

**Issue by ozh** [rmccue/Requests#145]
Hi Ryan

In [library/Requests/Transport/fsockopen.php#L213:L216](https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/fsockopen.php#L213:L216) we have:
```php
$this->info = stream_get_meta_data($fp);
$this->headers = '';
$this->info = stream_get_meta_data($fp);
```

Is there any reason for these 2 consecutive `stream_get_meta_data()` ? I don't think the result can ever differ.

**Comment by rmccue** [comment]
I think you're right, doesn't seem like there's any reason for this. Thanks :)
