### ISSUE TITLE
Possible bug in Requests.php compatible_gzinflate() function

### ISSUE THREAD

**Issue by adam-pro** [rmccue/Requests#151]
Regarding function: compatible_gzinflate()   
LINES 815 to 818 currently read:

```
815    if ( ! $zip_compressed_on_the_fly ) {
816        // Don't attempt to decode a compressed zip file
817        return $gzData;
818    }
```
POTENTIAL ISSUES
The following look wrong to me:
(1) The test on line 815, given the comment at Line 816
(2) Returning unprocessed $gzData at line 817.

The code should perhaps read:
```
815    if ( $zip_compressed_on_the_fly ) {
816        // Don't attempt to decode a compressed zip file
817        return false;
818    }
```

**Comment by rmccue** [comment]
This behaviour is correct; it's checking if it's a compressed response, or if it's a zip file. If it's a zip file, `zip_compressed_on_the_fly` will be false, so the data we received is uncompressed-on-the-fly (but happens to be a zip file), hence we return it.

Thanks for filing the issue :)
