### ISSUE TITLE
Make Requests_Transport_cURL::stream_headers accessible

### ISSUE THREAD

**Issue by adri** [rmccue/Requests#157]
While fixing [this issue in php-vcr](https://github.com/php-vcr/php-vcr/issues/115) I noticed that a [curl header function](https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/cURL.php#L272) references the protected function [Requests_Transport_cURL::stream_headers](https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/cURL.php#L306). 

This works as long as the caller of the callback is in the same "class scope" but not when calling it from somewhere else like php-vcr does. When running the [integration tests](https://travis-ci.org/php-vcr/php-vcr/jobs/61653312) I get the following error:

```
Invalid callback Requests_Transport_cURL::stream_headers, cannot access protected method Requests_Transport_cURL::stream_headers()
```

When I make the method public, it works. Would you like to do this or would you prefer another way to allow for calling this method?

**Comment by ozh** [comment]
(semi-related, sorry for hijacking: @rmccue, ditch 5.2 and use this neat PHP-VCR to solve the ongoing external HTTP request!!)

**Comment by adri** [comment]
@ozh At the moment php-vcr can't intercept `fsockopen` or `stream_socket_client`, see the [issue on php-vcr](https://github.com/php-vcr/php-vcr/issues/109). Using php-vcr for Requests would work only for the cURL part. In theory "raw requests" can also be intercepted but I couldn't find the time yet to implement it.

Btw. PHP 5.3+ would only be necessary for running tests, not for the library itself.
