### ISSUE TITLE
Issue with multiple requests

### ISSUE THREAD

**Issue by mrd05d** [rmccue/Requests#160]
I have been trying to get the request multiple function to work and cant seem to get it working.
```php
<?php
require_once 'Requests-1.6.0/library/Requests.php';
Requests::register_autoloader();

// $arrayName = array("www.google.com","yahoo.com");
$arrayName = array('http://www.google.com','http://www.yahoo.com');
// var_dump($arrayName);
$responses= Requests::request_multiple($arrayName);

?>
```

I receive the following:
```
Fatal error: Cannot use string offset as an array in /Applications/AMPPS/www/franks/Requests-1.6.0/library/Requests.php on line 394
```

**Comment by rmccue** [comment]
As noted in [the documentation](http://requests.ryanmccue.info/api/class-Requests.html#_request_multiple):

> The `$requests` parameter takes an associative or indexed array of request fields.
> [...]
> The request fields value is an associative array with the following keys:

So, you need to instead use:
```php
$arrayName = array(
	array(
		'url' => 'http://www.google.com',
	),
	array(
		'url' => 'http://www.yahoo.com',
	),
);
```

**Comment by mrd05d** [comment]
I apologize for misunderstanding the api documentation. I didn't realize i
needed an array of arrays as you have shown. I see the other fields have
defaults set to a blank array. Does this mean they are optional? I have
tried passing the new array of arrays as you have documented but i get a
request exception object that even if i pass it a one item array. Is there
any simple examples anywhere for the multiple requests function?

    [type:protected] => requests.no_crlf_separator
    [data:protected] =>
    [message:protected] => Missing header/body separator
    [string:Exception:private] =>
    [code:protected] => 0
    [file:protected] =>
/Applications/AMPPS/www/franks/Requests-1.6.0/library/Requests.php
    [line:protected] => 544
    [trace:Exception:private] => Array
    ...
