### ISSUE TITLE
Has HTTPS support been disabled?

### ISSUE THREAD

**Issue by beutnagel** [rmccue/Requests#161]
@rmccue, it throws a Request_Exception when using HTTPS urls. Has HTTPS support been disabled?
![image](https://cloud.githubusercontent.com/assets/1915772/8224502/6ae88cdc-1588-11e5-9f55-8dff98c885c1.png)

**Comment by rmccue** [comment]
That regular expression matches `http://` or `https://`. Check the `$url` value that you're passing in, as it seems like it doesn't match either of those.

**Comment by beutnagel** [comment]
Alright, thank you! Got it. 

I just misunderstood the error message, as it says only HTTP requests and figured that https was then not supported.

**Comment by rmccue** [comment]
Yeah, it's because HTTPS is really just `TLS( HTTP )` :)

**Comment by beutnagel** [comment]
Make sense (now). Once again, thank you very much!

**Comment by ozh** [comment]
This said, might make sense to update the error message to "Only HTTP(S) requests are handled"

**Comment by rmccue** [comment]
Indeed, that'd help to clarify it a bit more. :)

**Comment by ozh** [comment]
@beutnagel this means "please make a PR with an updated message" ;)
