### ISSUE TITLE
cURL's interface was not designed for PHP 4

### ISSUE THREAD

**Issue by davidstrauss** [rmccue/Requests#166]
The interface in PHP is just a thin wrapper of the C library interface. I'm not sure that would have been done differently if someone created a fresh cURL extension for PHP 5.x. A high-level, object-based wrapper is great, but a procedural one is sometimes the right choice (at least for the initial bridge into PHP land) if the underlying library is, itself, procedural.

For example, in python-systemd, we expose systemd's C-based logging functions to Python as procedural functions and then provide Pythonic objects via regular Python code. It's not PHP, but it's an example of why you wouldn't go all the way from a procedural library to high-level objects in one swoop.

**Comment by rmccue** [comment]
Absolutely true that the functions are C API wrappers, but if the extension was designed today, I almost guarantee it'd include an OOP API as well. The fact that we have both procedural calls with `curl_setopt` _as well_ as the newer [`CurlFile`](http://php.net/manual/en/class.curlfile.php) API indicates that it'd probably be a good idea.

Low-level APIs are great, but regular developers shouldn't be using them unless they're maintaining a HTTP library. :)

Thanks for the comment!
