### ISSUE TITLE
Download , Stream file example !

### ISSUE THREAD

**Issue by jimmyphong** [rmccue/Requests#168]
Any example using Request class to download a zip file and put it to temp folder of our project !
Thanks

may be example download another file type (like zip, image, video ...)

**Comment by rmccue** [comment]
The following should work:

```php
Requests::get( 'http://example.com/file.zip', array(), array( 'filename' => dirname( __FILE__ ) . '/localfile.zip' ) );
```

**Comment by subins2000** [comment]
When I try to download a file, before it is downloaded timeout error occurs. How can I disable timeout ?

Shouldn't timeout be automatically disabled when handling file downloads ?

**Comment by subins2000** [comment]
@rmccue Is timeout disabled when handling file downloads ?
