### ISSUE TITLE
Allow browser-compatible handling for 302

### ISSUE THREAD

**Issue by rmccue** [rmccue/Requests#178]
Right now, 302s are handled the same as 307s: a POST will redirect to a new URL as a POST. Browsers usually treat 302s as a 303 however: a POST will redirect to a new URL as a GET instead.

I'm tossing up between changing behaviour, and adding a new flag. To ponder...

**Comment by rmccue** [comment]
This is possible with #205:

```php
$options['hooks']->register( 'requests.before_redirect', 'browser_redirect_compatibility' );

function browser_redirect_compatibility( $location, $headers, $data, &$options, $original ) {
		// Browser compat
		if ( $original->status_code === 302 ) {
				$options['type'] = Requests::GET;
		}
}
```

**Comment by asesidaa** [comment]
Hi, any plan to integrate this as a built-in function? Or maybe add this as an example in documentation. I believe this function is quite useful
