### ISSUE TITLE
Request doesn't set the user agent properly ?

### ISSUE THREAD

**Issue by Ugo-PK** [rmccue/Requests#195]
While debugging my scraper, built with this library, I hit a dead end trying to get a json by xmlhttprequest. Simple check proved me a curl command was working, so it was somewhere within the code. I added some option in cURL.php to check the headers sent by the lib (around line 115).

<pre>
curl_setopt($this->fp, CURLINFO_HEADER_OUT, true); // enable trackinginfo debug

$response = curl_exec($this->fp);
                
echo  'curl:'.json_encode(curl_getinfo($this->fp, CURLINFO_HEADER_OUT), JSON_PRETTY_PRINT)';
</pre>
It appeared that user agent was set to "php-requests\/1.6.1" and referer to url I was accessing, not last one.

I set my options through session object, dunno if problem come from there, but it seems there's a bug around here. None of the following seem to work:
<pre>
 $session->useragent = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0';
        $session->headers["UserAgent"] = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0';
        $session->options["useragent"] = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0';
</pre>

**Comment by rmccue** [comment]
Can you please give your full code example of how you're using Requests?

**Comment by Ugo-PK** [comment]
$c = new \Requests_Cookie_Jar([]);
        //use a session object for requests
        $session = new \Requests_Session('https://business.idealo.com/');
        $session->useragent = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0';
        $session->options = ['cookies' => $c];
        $response = $session->get('/login', [], [] );


Adding a var_dump on the $options, line 318 of Requests.php, I get : 

array (size=16)
  'timeout' => int 10
  'useragent' => string 'php-requests/1.6.1' (length=18)
  'redirected' => int 0
  'redirects' => int 10
  'follow_redirects' => boolean true
...

**Comment by rmccue** [comment]
Your call to set `->options` is overwriting the options previously set (i.e. useragent). You can move the useragent line below the options set call, or set useragent in the options array.
