### ISSUE TITLE
detected a problem with the transmission of cookies between subdomains domain

### ISSUE THREAD

**Issue by blizzardkem** [rmccue/Requests#197]
if the server has set a cookie type .domain.com, it should work on all subdomains of the domain, for example test.domain.com.
however, in your script you have a condition that prevents this work (cut off point at the beginning of a domain):
                     // Domain normalization, as per RFC 6265 section 5.2.3
                     if ($ value [0] === '.') {
                          $ value = substr ($ value, 1);
                     }

As a result, the cookie is only to domain.com, even if it has been assigned to all subdomains of the domain.

**Comment by blizzardkem** [comment]
Correction
========

...
case 'domain':
	// Domain normalization, as per RFC 6265 section 5.2.3
	if ($value[0] === '.') {
// added by blizzard 14/07/2015 3:40
//		$value = substr($value, 1);
// added by blizzard 14/07/2015 3:40
	}
break;
...

...
$domain_string = $this->attributes['domain'];
if ($domain_string === $string) {
	// The domain string and the string are identical.
	return true;
}

// added by blizzard 14/07/2015 3:40
if ($domain_string{0} == '.' AND (preg_match('/'.$domain_string.'$/i', $string) OR substr($domain_string, 1) == $string))
{
	return true;
}
// added by blizzard 14/07/2015 3:40

// If the cookie is marked as host-only and we don't have an exact
// match, reject the cookie
.....

**Comment by blizzardkem** [comment]
Implementation at guzzle
https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Plugin/Cookie/Cookie.php#L450L466

**Comment by blizzardkem** [comment]
Cut a point - you can not
It is also necessary to mark that the check is made on the sub-domains, such as $subdomain = TRUE;
And then do the checking, for example, as did I - preg_match

**Comment by rmccue** [comment]
Per [RFC 6265](http://tools.ietf.org/html/rfc6265#section-5.2.3):

```
If the first character of the attribute-value string is %x2E ("."):

   Let cookie-domain be the attribute-value without the leading %x2E
   (".") character.
```

That is, cookies set for `example.com` are exactly the same as those for `.example.com`. These are both handled later in [`Requests_Cookie::domain_matches`](https://github.com/rmccue/Requests/blob/2d7dc0b81018f421456909b3ab8d8ab8df11d6a4/library/Requests/Cookie.php#L137).

Note that Guzzle is doing the same handling here and removing the leading dot.

The code here should be working correctly; do you have examples that this does not work with?

**Comment by blizzardkem** [comment]
That's right, the point is removed, but note that this applies to all subdomains

**Comment by blizzardkem** [comment]
I painted all the details

**Comment by rmccue** [comment]
Correct, the dot is always removed, which is the correct behaviour. This means that cookies set for any domain will work on any subdomains of that domain as well. The only way to _not_ have this behaviour is to not include a `domain` attribute in the cookie, which triggers the `host-only` flag. (See [step 6 of section 5.3](http://tools.ietf.org/html/rfc6265#section-5.3) in the RFC.)

Again, without an example of what's failing here, I can't help further. :)

**Comment by blizzardkem** [comment]
I have already cited the example of how to solve this bug, you're a programmer, it is not clear?

**Comment by blizzardkem** [comment]
I understand I find it easier to conduct parallel reworked your design

**Comment by blizzardkem** [comment]
So it should work: 
We present the number of streams
Add 1 link
as soon as the number of threads is exceeded, we expect the answer (get it in kalbeke)
Once it became less in the links, add another

**Comment by blizzardkem** [comment]
setcookie("TestCookie", 1, time()+3600, "", ".example.com", 1);

Get http://example.com - TestCookie = 1
Get http://www.example.com - no cookie...

заебись у тебя работает, ага ))

**Comment by rmccue** [comment]
> I have already cited the example of how to solve this bug, you're a programmer, it is not clear?

The comments above have changes to Requests code, but there's no examples of what exactly isn't working for you. I can't change the code without understanding what the issue is.

Can you please post the code you're using with Requests to send these requests? It's possible that the cookie jar isn't shared between the requests.
