### ISSUE TITLE
Small caps http verb don't work as expected

### ISSUE THREAD

**Issue by 73sl4** [rmccue/Requests#204]
Hello,

I was using request specific function `post()/get()` but then I decided to shift to `request()` but I mistakenly forgot to uppercase the HTTP verbs and type was going as `post/get` which was not recognised by `cURL Transport`.
I think `post` should work same as `POST`, it should be case insensitive.

**Comment by rmccue** [comment]
Requests actually only supports the constants (`Requests::POST` etc), but we should do this just so it's easier to use. I'll patch :)

**Comment by 73sl4** [comment]
Yes, we can uppercase the value of `$type`. Let me know if you need me for a PR or any update.
