### ISSUE TITLE
curl error #28

### ISSUE THREAD

**Issue by 119786155** [rmccue/Requests#213]
`local.ERROR: exception 'Requests_Exception' with message 'cURL error 28: Operation timed out after 10000 milliseconds with 83 out of 83 bytes received' in vendor/rmccue/requests/library/Requests/Transport/cURL.php:280`

**Comment by rmccue** [comment]
This exception indicates your connection timed out. Have you tried with a higher timeout on the request?

**Comment by 119786155** [comment]
em, it is ahout ngnix & php-fpm，so I will close the issue

**Comment by philip** [comment]
One way to increase the cURL timeout is to set the `Requests` timeout option, which takes a number of seconds e.g., `$options['timeout'] = 120;` ... it (essentially) defaults to 10.

**Comment by arcdestudio** [comment]
> One way to increase the cURL timeout is to set the `Requests` timeout option, which takes a number of seconds e.g., `$options['timeout'] = 120;` ... it (essentially) defaults to 10.

Hello philip! From where can we increase it?

**Comment by pyalpha** [comment]
i got the same errors ! any help how to increase this limits ? thx

**Comment by xrobau** [comment]
The options param is the third - `\Requests::get("https://example.com", ["Accept" => "text/plain"], ["timeout" => 30]);`

See https://github.com/rmccue/Requests/blob/master/library/Requests.php#L230
