### ISSUE TITLE
Auto use Proxy if HTTP_PROXY & HTTPS_PROXY Environment variable is set

### ISSUE THREAD

**Issue by c33s** [rmccue/Requests#218]
not sure if it should be part of this lib or if the handling of env variables should be part of the apps using this lib. comming from https://github.com/wp-cli/wp-cli/issues/3019

> if try to run wp core download it connects directly not using the exported proxy. so it runs in a timeout because of the lan setting only allowing to connect to the net trough the proxy.
> so reading the proxy settings from the env variables and connection through that proxy would be awesome, because then it could be used in proxied & firewalled environments.

answer:
> wp core download uses the Requests library to make remote requests. I'd suggest opening a ticket with that project to discuss supporting the environment variables.

**Comment by Rarst** [comment]
This (using `HTTP_PROXY` environment var) seems to be making rounds as major security vulnerability, see https://httpoxy.org/

**Comment by rmccue** [comment]
Indeed; in light of the security vulnerability, I think it's probably a good idea to stay away from mixing in global state. You can pass in proxy information with a request, or use a Session object to keep it around as needed.

**Comment by c33s** [comment]
the security issue is about putting the http proxy from the header to the environment. what i ask for is having the option, that the lib _can_ read the proxy env variable if wanted. like many other linux tools like wget.

also for me it feels wrong to not implement a feature because of a security issue which can simply blocked by not allowing the webserver to set the environment variable (not the opposite of letting a php script read an env variable)

its like "we have to remove the feature of opening files with php, because someone could inject bad files. or we have to forbid cars, because there is alcohol and people could use alcohol and then drive the car.

reading the HTTP_PROXY is common see https://httpoxy.org/
> HTTP_PROXY is a popular environment variable used to configure an outgoing proxy

as a maintaining such a cool libary you should support standards. libaries should prevent developers from repeating themself. adding this feature to your lib for example makes it possible to use https://github.com/wp-cli/wp-cli/ behind a proxy. so having a phar file works out of the box without any other config. if your keep your lib like it is, everyone who uses your lib has to implement the same feature of supporting the `HTTP_PROXY` variable.

**Comment by Rarst** [comment]
As far as I follow it's perfectly possible to make requests with a proxy already http://requests.ryanmccue.info/docs/proxy.html it is up to downstream code to call it as necessary.

Implementing it via global state which is **known** to be a security issue isn’t an enhancement.

**Comment by rmccue** [comment]
Requests is intended for usage in all types of environments, including both web and CLI. I'd rather not bring in any of the environment state unless necessary.

wp-cli can implement the environment variable as needed, because it knows it's running via the CLI context, so it's not a security issue at that level. Requests is too low-level to make those assumptions.

wp-cli can use it pretty easily:
```php
$parsed = parse_url( getenv( 'HTTP_PROXY' ) );
$proxy = $parsed['host'];
if ( ! empty( $parsed['user'] ) ) {
    $proxy = [ $proxy, $parsed['user'], $parsed['pass'] ];
}

$options = array(
    'proxy' => $proxy,
);
```

**Comment by c33s** [comment]
as i said, not adding a feature because of a security issue which exists currently feels really wrong.

> https://secure.php.net/ChangeLog-7.php#7.0.9
> Fixed bug #72573 (HTTP_PROXY is improperly trusted by some PHP libraries and applications).

of course everyone who use the lib can configure it and add the same code over and over again. 
parse the url if its http or https, try read the `HTTP_PROXY` or `HTTPS_PROXY` variable and then add the config as @rmccue posted above. but that is not [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). 

in fact from security side, the `HTTP_PROXY` part should be part of your lib because if everyone who uses the lib has a self coded `HTTP_PROXY` handling, everyone has to patch their own app and maintain the proxy code.

if its part of your lib, you can release a security fix/workaroud and everyone who uses the lib via composer like `x.y.*` automatically has a fix until the webserver/php developer add a fix in their products.
also instead of reporting a possible risk here in the ticket, a person can add a potential risky version [here](https://security.sensiolabs.org/contribute) and erveryone who is using the [security checker](https://github.com/sensiolabs/security-checker) will see that there is a risk.

the big advantage is that it only needs to be fixed in one place and not in every single app which is using your lib. it is far more likely that someone reports a security issue for this lib and we come to a fix quite fast instead of waiting for every app to implement a fix.

compareable to that is the requested feature part, its more likely that everone is profiting from a global (in this lib) implemented `HTTP_PROXY` handling, then wait for every app which is using it to implement their handling. see https://github.com/wp-cli/wp-cli/issues/3019 @danielbachhuber is right, wp-cli is the wrong part to implement the proxy handling.

i think reading `HTTP_PROXY` should be default, which leads that every app which is using the lib works out of the box with zero config in a proxied environment (compony env) for people who don't want that, there should be a config:

```
$options = array(
    'proxy_env' => false,
);
```

@danielbachhuber maybe you also want to add your 5cts from a viewpoint of a developer who is using this lib.

**Comment by danielbachhuber** [comment]
> maybe you also want to add your 5cts from a viewpoint of a developer who is using this lib.

Sure. Supporting `HTTP_PROXY` isn't something I see a need for. I agree with @rmccue and @Rarst.

**Comment by dnmvisser** [comment]
Not supporting HTTP_PROXY breaks functionality in environments that use it. Everything @c33s says is right. All existing command line programs use it and for good reasons: security. So should wp_cli. Currently I have to bootstrap WP instances *manually* using curl or wget (a universally used tool that does honour `http_proxy`), unpack, create `wp-config.php` to include the `WP_PROXY_HOST` and `WP_PROXY_PORT`, use curl or wget again to role some keys and salts through the https://api.wordpress.org/secret-key/1.1/salt/ service.
Basically I'm duplicating parts of `wp_cli` in shell scripts/ansible/etc. 
Please reopen this issue so it can be fixed.

**Comment by rkok** [comment]
Can you _please_ support http proxying, at least as a command-line argument? It's quite common for corporate build servers to require a proxy for outgoing traffic; this is the situation I'm in currently, and I reckon a lot of other developers, too.

**Comment by c33s** [comment]
for reference: https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/
