### ISSUE TITLE
how to use the library to upload file?

### ISSUE THREAD

**Issue by jonny77** [rmccue/Requests#221]
Array
(
    [media] => CURLFile Object
        (
            [name] => /var/www/test/public/uploads/tmp_image/804766a60ab6bd006ca76fc68ac3e744.jpg
            [mime] => 
            [postname] => 
        )

)

**Comment by toohamster** [comment]
Why don't you try https://github.com/toohamster/ws-http

**Comment by rmccue** [comment]
Currently, you need to load the file's content as a string:

```php
$content = file_get_contents( $filename );
```

#34 tracks the ability to use a file stream instead.
