### ISSUE TITLE
URLs with double slash at the start of the path fail to be requested

### ISSUE THREAD

**Issue by dd32** [rmccue/Requests#231]
`Requests_IRI` currently rejects a url such as `http://example.org//path/` as being valid, but accepts `http://example.org/path//path/`.

This seems to stem from this bit of code: https://github.com/rmccue/Requests/blob/master/library/Requests/IRI.php#L691-L694

I haven't looked at it close enough to determine if it's a logic error in the if statement, or if it's an edgecase it's specifically not attempting to support. At first I thought it was trying to catch the case where the scheme separator was picked up as the path component.

This [was reported](https://wordpress.org/support/topic/wp_remote_get-is-not-working-after-wordpress-update-to-46) as a regression in WordPress 4.6, as we previously handled this scenario before we switched to Requests.

**Comment by rmccue** [comment]
I'm unsure why this code exists here; I suspect it's an intricacy in the IRI spec. I didn't write this code however, this is ported from SimplePie's IRI parser, which was written by @gsnedders. I'm wondering if it's meant to be caught at a higher level.

We can probably fix this with no real issues.

**Comment by rmccue** [comment]
Tracked back to [this commit](https://bitbucket.org/gsnedders/iri/commits/cc7d1532e1b5c9b499bd007d5c1354e3473e1dd6).

**Comment by orange-themes** [comment]
Seems like not only double path, we get the same error, when we try to access http://www.geoplugin.net/json.gp?ip=8.8.8.8

The response is like http://grab.by/Sq3i and this happened direct after wp update to 4.6

**Comment by rmccue** [comment]
@orange-themes I think this is unrelated; might be #232 if the server you're connecting to checks referer headers.

**Comment by gsnedders** [comment]
@rmccue Pretty sure I just misread the RFC, because this should totally work. More seriously, we probably just want to follow [this](https://url.spec.whatwg.org) given it roughly matches what browsers do.

**Comment by rmccue** [comment]
@gsnedders Thanks for the confirmation; my guess is it was just a double-check on higher-level normalisation. Will fix now :)
