### ISSUE TITLE
Can we add the transport used to the response output?

### ISSUE THREAD

**Issue by reidbiztech** [rmccue/Requests#233]
I am having a devil of a time figuring this beast out. Knowing what transport was used would be most helpful.

**Comment by reidbiztech** [comment]
Perhaps I should explain why I ask: I am the author of https://wordpress.org/plugins/reid-plugins-curl-options/ and I am updating the plugin to deal with this new Requests library usage in WP.

I have modified my plugin thus:
```php
	if ( version_compare( $wp_version, "4.6", ">=" ) ) {
		if ( class_exists( 'Requests' ) ) {
			$rpco_requests_hooks = new Requests_Hooks();
			$rpco_requests_hooks->register( 'curl.before_send', 'rpco_http_api_curl', PHP_INT_MAX );
		}
	} else {
		add_action( 'http_api_curl', 'rpco_http_api_curl', PHP_INT_MAX, 1 );
	}
```

but my curl options no longer seem to take. :( I cannot seem to figure out why. I have even tried commenting out the Requests_Transport_fsockopen transport in the Requests class trying to temporarily force curl, but no joy. 

A curl request to the paypal sandbox works every time now and I have no idea why. Even when I set CURLOPT_SSLVERSION to 2 or 3 paypal still responds like everything is fine.

Perhaps I am not catching the curl resource handle the same way as the old WordPress action did?

**Comment by ramesh-tr** [comment]
A bit late reply, but could be helpful for others as well. 

There is a way to specify a transport using the options while making a request. 

```
$options = array(
    'auth' => new MySoftware_Auth_Hotdog('yummy'),
    'transport' => 'Requests_Transport_cURL'
);
$response = Requests::get('http://hotdogbin.org/admin', array(), $options);

```
This is really helpful to force the traffic through specific transport channel when we deal with transport based hooks (something like curl.before_send etc).

**Comment by reidbiztech** [comment]
Thanks for the reply ramesh-tr. I was aware of that, but unfortunately it is of no use to me, because I am not the one calling the requests library. WordPress and its multitude of possible plugins is. In particular I am most concerned with WooCommerce payment gateway extensions. Which use the WordPress HTTP API. 

Interestingly I have notices that the WooCommerce Square extension has recently abandoned trying to use the WordPress HTTP API after the change in WP 4.6 to include and use the Requests library. WooCommerce Square is now manually building and calling PHP cURL functions directly, presumably to account for the new and unexpected behaviour of the Requests library as used in WordPress.

**Comment by reidbiztech** [comment]
I think I now see my problem (RTFMS applies)... in the Requests Hooks documentation it specifies that any created hooks must be passed to Requests when invoked:

```php
$hooks = new Requests_Hooks();
$hooks->register('requests.after_request', 'mycallback');

$request = Requests::get('http://httpbin.org/get', array(), array('hooks' => $hooks));
```
https://github.com/rmccue/Requests/blob/master/docs/hooks.md

I seem to have missed that in my first go at this. (see code in my second comment above)

So now in order to register my hook in WordPress, I think I may need to modify the WordPress core code, thus completely defeating the entire purpose of hooks. What a pain...

**Comment by reidbiztech** [comment]
Yup, looking at the WP_Http class, looks I need to make a feature request at WordPress to add WP hooks (actions/filters) to access Requests hooks. (Yo, dawg, I heard you like hooks...)

**Comment by ramesh-tr** [comment]
I think you can intercept the http request by using wordpress 'pre_http_request' filter. Do the http traffic from your plugin using the Requests, and have the luxury of using your own hooks to set cURL options.

**Comment by reidbiztech** [comment]
That's not a bad thought. Thanks for the suggestion! However, this issue is now being addressed here:

https://core.trac.wordpress.org/ticket/37843

So I won't need to make such a major change to my plugin. :)

**Comment by rmccue** [comment]
The actual problem here is fixed on the WordPress side with the newer hooks that are available.
