### ISSUE TITLE
curl.before_request Missing argument 2 for ::before_request()

### ISSUE THREAD

**Issue by adampatterson** [rmccue/Requests#234]
Registering a before request authentication using curl.before_request gives me Missing argument 2 for ::before_request(). 

I'm using Laravel and an exact copy of the MySoftware_Auth_Hotdog example. https://github.com/rmccue/Requests/blob/master/docs/authentication-custom.md

I am not clear on how I can specifically choose to use CURL but I am attempting to send a header something like

`Authorization: f89sdyf98sdfh9ds`

The services that I am trying to authenticate with has nothing about how you are supposed to actually authenticate with them so it's entirely possible that it's my issue.

But when I use the command line:

`curl -H "Authorization:f89sdyf98sdfh9ds" https://podium.co/api/v2/organizations/{special}/locations` 

Everything works as expected.

Thanks for any possible help.

**Comment by ramesh-tr** [comment]
You can specifically choose to use CURL by specifying the 'transport' option as in the following example

```
$options = array(
    'auth' => new MySoftware_Auth_Hotdog('yummy'),
    'transport' => 'Requests_Transport_cURL'
);
$response = Requests::get('http://hotdogbin.org/admin', array(), $options);
```

**Comment by adampatterson** [comment]
That's exactly what I was doing. The service that I was trying to connect to had no documentation and their API examples also did not work properly. 10 hours later everything fixed itself.  Best kind of Bug!
