### ISSUE TITLE
PHP Fatal error - SSL3_GET_KEY_EXCHANGE:unable to find ecdh parameters

### ISSUE THREAD

**Issue by ivary** [rmccue/Requests#247]
Hi,

Since today i get the following error (apache error_log), yesterday my skript worked perfectly:

`PHP Fatal error:  Uncaught exception 'Requests_Exception' with message 'cURL error 35: error:1408D13A:SSL routines:SSL3_GET_KEY_EXCHANGE:unable to find ecdh parameters' in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php:277\nStack trace:\n#0 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php(120): Requests_Transport_cURL->process_response(false, Array)\n#1 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(317): Requests_Transport_cURL->request('https://de.wiki...', Array, NULL, Array)\n#2 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(600): Requests::request('https://de.wiki...', Array, NULL, false, Array)\n#3 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(321): Requests::parse_response('HTTP/1.1 301 TL...', 'http://de.wikip...', Array, NULL, Array)\n#4 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(600): Requests::request('http://de.wikip...', Array,  in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 277`

with https-Adress i get the following:

`PHP Fatal error:  Uncaught exception 'Requests_Exception' with message 'cURL error 35: error:1408D13A:SSL routines:SSL3_GET_KEY_EXCHANGE:unable to find ecdh parameters' in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php:277\nStack trace:\n#0 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php(120): Requests_Transport_cURL->process_response(false, Array)\n#1 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(317): Requests_Transport_cURL->request('https://de.wiki...', Array, NULL, Array)\n#2 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Session.php(202): Requests::request('https://de.wiki...', Array, NULL, 'GET', Array)\n#3 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Session.php(129): Requests_Session->request('https://de.wiki...', Array, NULL, 'GET', Array)\n#4 /srv/www/htdocs/locations/new/vendor/hamstar/wikimate/Wikimate.php(206): Requests_Session->get('https://de.wiki...')\n#5 /srv/ in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 277`

Does someone else gets that error?

**Comment by rmccue** [comment]
It's likely that the site you're accessing changed their SSL configuration, and your system's SSL version is out of date. Try upgrading cURL/OpenSSL.

There's not much we can do about this (and this is also an older issue), so closing it out.
