### ISSUE TITLE
Getting Error while using the library with SLIM 

### ISSUE THREAD

**Issue by ashickurnoor** [rmccue/Requests#253]
I am trying to use this library with in my application which is develop by using [SLIM](http://slimframework.com/) to call a external API. But when I tried to execute the library in my app I am getting this error.

<pre>
The application could not run because of the following error:
Details
Type: Requests_Exception
Message: Only HTTP(S) requests are handled.
File: /Users/noor/Sites/binameer/api/vendor/rmccue/requests/library/Requests.php
Line: 564
</pre>

sample code 

```
<?php
Requests::register_autoloader();
$url = 'https://api.infobip.com/sms/1/text/single';
$headers = array('accept' => 'application/json','content-type' => 'application/json','authorization' => 'Basic cmVhenVsbGFoOkZxdnA5aUtB');

$app->put('/newsponser', function ($request,$response,$args) {

    $ResponseSuccessArray=array();
    $DescArray=array();
    $DescArray['sponserid']='123';
    $ResponseSuccessArray['status']="true";
    $ResponseSuccessArray['type']="sponser";
    $ResponseSuccessArray['id']="85";
    $ResponseSuccessArray['attributes']=$DescArray;
    $returnArray['data']=$ResponseSuccessArray;
    $data = array("from"=>"b","to"=>"+8801972255155","text"=>"Test SMS");
    $responses = Requests::post($url, $headers, json_encode($data));
    var_dump($responses);
    return $response->withJson($returnArray,201);


});


```

**Comment by rmccue** [comment]
Variables in anonymous functions need to be explicitly scoped in PHP, so you need to have `function ($request, $response, $args) use ($url) {` otherwise `$url` will be undefined in your callback.
