### ISSUE TITLE
Update readme to mention PSR-4 autoloader instead of PSR-0

### ISSUE THREAD

**Issue by ptasker** [rmccue/Requests#281]
PSR-0 is dead, long live PSR-4!

http://www.php-fig.org/psr/psr-4/

**Comment by rmccue** [comment]
Since Requests isn't namespaced, I don't think we can use PSR-4?

**Comment by ptasker** [comment]
You are right, totally didn't think of that. Namespaces are definitely required for PSR-4. Closing.
