### ISSUE TITLE
Move away from composer.phar in unit tests, to using local phpunit installation of < 6.0

### ISSUE THREAD

**Issue by TysonAndre** [rmccue/Requests#282]
https://docs.travis-ci.com/user/docker/

PHPUnit will likely keep adding new backwards incompatible changes. Locking the required version to < 6.0 will reduce future maintenance work and hopefully make build status more predictable.

**Comment by rmccue** [comment]
Do you have an existing container we could use in mind?

**Comment by TysonAndre** [comment]
No, I hoped they'd have official prebuilt images, but they don't

- Centos images have 5.3 and 5.4, but probably not 5.0. There are experimental 70 builds in a sub-project
- phpunit doesn't have tags tagged by php version.
- We can try building php from source (in ~3 minutes per build) with a new GCC version : 
 https://github.com/igbinary/igbinary/blob/master/.travis.yml (This is from another php project I work on)
  (Again, this will make out tests of different libcurl weaker, but it's also possible to build libcurl from source if we care)

If we build from source, then the "travis cache" feature may help (You can upload the compiled binaries, usually helps only if those are smaller than what was used to compile them.

(Can also install different composer releases the same way)

**Comment by rmccue** [comment]
(FWIW, I started on a [PHP build tool](https://github.com/rmccue/phpbuild) a long time ago to make it easier to install PHP and specific versions of cURL/etc, but it never ended up going anywhere since I didn't have the time for it.)

Worth mentioning that we could lock just the PHPUnit version without using Docker by using a PHAR directly instead. PHP doesn't tend to break on us (much).

**Comment by jrfnl** [comment]
I'm going to close this issue. The tests will need to be made cross-version compatible with a wider range of PHPUnit versions to be able to run the tests on PHP 8.
If PHP 5.2 still needs to be supported, this range will need to be PHPUnit 3.x - 9.x.
If PHP 5.6 would become the new minimum supported version, the range will need to be PHPUnit 5.x - 9.x. Either way, running the tests on PHP 8 with PHPUnit < 6 is not an option.
