### ISSUE TITLE
How do I upload a file?

### ISSUE THREAD

**Issue by zhaoheng** [rmccue/Requests#285]
I looked at the document and found no instructions for uploading files;

So, if anyone will, please let me know, thank you

**Comment by ozh** [comment]
You can probably start by [searching previously opened (and answered) issues](https://github.com/rmccue/Requests/search?q=upload+file&type=Issues&utf8=%E2%9C%93).

This said, given the number of occurences of this matter, I guess it would make sense to add an example to the docs :)
