### ISSUE TITLE
PHP on windows and request.php

### ISSUE THREAD

**Issue by pkonings** [rmccue/Requests#286]
I installed both php on my raspberry and windows. Using the CLI I a simple (see below) works successfully on Unix but not on windows. I get a "Fatal error: Class not found" etc. . I installed Requests as a subfolder and in th e windows php directory. I guess the W10 environment needs a .dll to use it as a extension. So far my best guess goes, but need some direction to understand where to look for. Any ideas?

<?php
include('Requests/Requests.php');
Requests::register_autoloader();
$request = Requests::get('http://www.weeronline.nl/');
var_dump($request);
?>

**Comment by ozh** [comment]
Requests is just a PHP script. Your problem depends on how you installed PHP (webserver, document root, etc...) and absolutely not on Requests itself, and Requests definitely does not need anything special for Windows.

Again, this is just a PHP script. A little bigger than `<?php echo('hello world'); ?>` but nothing different in terms of requirements.

Does `<?php echo('hello world'); ?>` works on your Windows server?
