### ISSUE TITLE
Multiple identifiers

### ISSUE THREAD

**Issue by skobeo** [rmccue/Requests#287]
when doing multiple request is there a way to get something like the ID of each request in the response, to identify the object response. Cause, after tests, in the body i will have a json object, so ok, but the order can change depending of the timeout or the status. So off course i could return the ID from the server API which is requested, but seems to be more efficient to pass this ID into the request.
thanks

**Comment by ozh** [comment]
See [`multiple.php`](https://github.com/rmccue/Requests/blob/master/examples/multiple.php) in provided examples.

You can pass the id of a request as the key of the array of requests:

```php
$requests = array(
    // no key provided, so it will be [0]
    array(
        'url' => 'http://some.url/'
    ),
    // specify a key
    'this_one' => array(
        'url' => 'http://other.url/'
    ),
    // specify another key
    'this_other_one' => array(
        'url' => 'http://127.0.0.1/',
    ),
);
```

I think this answers your question. If not feel free to comment anyway.
