### ISSUE TITLE
Can't POST raw data

### ISSUE THREAD

**Issue by stumpyb** [rmccue/Requests#290]
In documentation it states that you can pass a string instead of array to POST raw data, but it doesn't work. Passing array works fine but passing a string results in many errors.

**Comment by soulseekah** [comment]
What sort of errors? If you want to send raw data, like json for example, you have to set the appropriate content type. For example:

`$response = Requests::post('https://httpbin.org/post', array('content-type'=>'application/json'), '1');`

Works perfectly fine. Passing just a string results in that string being interpreted as a form key with an empty value.
