### ISSUE TITLE
`testSNISupport` returning 502 for feelingrestful.com

### ISSUE THREAD

**Issue by soulseekah** [rmccue/Requests#308]
https://feelingrestful.com/ is down, CI is failing because of a 502 response in that test

**Comment by soulseekah** [comment]
wordpress.org is served with SNI and is guaranteed to be up

`openssl s_client -servername wordpress.org -tlsextdebug -connect wordpress.org:443 | grep "server extension"`

> TLS server extension "server name" (id=0), len=0

**Comment by rmccue** [comment]
Following up on this; it should definitely be online!

**Comment by rmccue** [comment]
Fixing this in #351. We brought the server back, but it then died again a bit later and is now 410 Gone.
