### ISSUE TITLE
Laravel Implementation

### ISSUE THREAD

**Issue by moxatgithub** [rmccue/Requests#322]
Anyone does implemented this to laravel?

**Comment by soulseekah** [comment]
This library is framework agnostic and can be used in Laravel.

**Comment by pkoziol** [comment]
It's used in [Firefly III](https://github.com/firefly-iii/firefly-iii/) for example.

**Comment by fanuch** [comment]
If you have Laravel 5.5+, all you need to do is `composer require rmccue/requests` in the root directory of your Laravel project.

Then do `use Requests;` at the top of your controller (or wherever).

I'm quoting `ixudra/Curl` where I found this info:
> Laravel 5.5+ Integration
> Laravel's package discovery will take care of integration for you.
