### ISSUE TITLE
Fatal Error: Uncaught exception

### ISSUE THREAD

**Issue by salasfoor** [rmccue/Requests#325]
Hi

I am getting an error when trying to post json data. The error is related to curl encoding. Our server has gzip enabled.

The error message: 

`Fatal error: Uncaught exception 'Requests_Exception' with message 'cURL error 61: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.' in /home/admin/public_html/translator/Requests/library/Requests/Transport/cURL.php:422 Stack trace: #0 /home/admin/public_html/translator/Requests/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response('', Array) #1 /home/admin/public_html/translator/Requests/library/Requests.php(379): Requests_Transport_cURL->request('https://sa-tran...', Array, '{"text":"This i...', Array) #2 /home/admin/public_html/translator/Requests/library/Requests.php(268): Requests::request('https://sa-tran...', Array, '{"text":"This i...', 'POST', Array) #3 /home/admin/public_html/translator/test_translate2.php(25): Requests::post('https://sa-tran...', Array, '{"text":"This i...') #4 {main} thrown in /home/admin/public_html/translator/Requests/library/Requests/Transport/cURL.php on line 422`

**Comment by soulseekah** [comment]
What content encoding are you trying to use when sending your request? Can you show some actual code, please?
