### ISSUE TITLE
Always get "Bad request (400)"

### ISSUE THREAD

**Issue by tonebender** [rmccue/Requests#335]
I just got started with Requests, using it with php5.6.

For some reason I get the response "Bad request" (400) on every GET and POST request I try.

I've tested this:
   $response = Requests::get('https://github.com/timeline.json');

with a number of URLs and they do respond (I get a github page) but they all say "Bad request" (400).

Tried with POST as well, the example in the docs:
			$url = 'https://api.github.com/some/endpoint';
			$headers = array('Content-Type' => 'application/json');
			$data = array('some' => 'data');
			$response = Requests::post($url, $headers, json_encode($data));
			var_dump($response->status_code);
But it also gives 400.

Sorry for the noob question, but where do I begin to find the cause for this?
Is it because I'm using php 5.6?

Thanks!

**Comment by soulseekah** [comment]
Looks like the bad request is coming from GitHub itself.
Try to do the same with https://requestbin.fullcontact.com/

**Comment by tonebender** [comment]
Thanks for the suggestion!
I tried it, and the request I make from php/Requests is so bad that it isn't even generating a report on requestbin.
I tried it with a simple curl command on the command line instead (on the same computer as the php/Requests application), and that worked fine, generating a report on the requestbin page.
But as I mentioned above I do get a response from the pages I try to request from php, so the request goes out at least.

**Comment by tonebender** [comment]
Just to be clear – it's not about github, I get "bad request" as response which ever webpage I try to request – google, yahoo, example.com. I also tried sending a request to my own webserver where I can check the access log, and it says the same there. In fact, this is all it says:
214.135.42.103 - - [02/Apr/2019:08:10:15 +0200] "GET / HTTP/1,1" 400 0 "-" "-"

**Comment by Zegnat** [comment]
```
0.0.0.0 - - [02/Apr/2019:08:10:15 +0200] "GET / HTTP/1,1" 400 0 "-" "-"
```
Is that the exact copy-paste from your access logs? Having a comma instead of a period as the decimal separator in the HTTP version looks super suspect. If that is what is being send, it is pretty obvious servers are responding with Bad Requests.

Could you try checking that you are using curl and not fsockopen as the transport? I think there may be a bug in fsockopen that makes it locale dependent… (If you have a locale set that uses commas for rendering floating point numbers, those will be used in the HTTP line.)

**Comment by rmccue** [comment]
Sorry, I can't offer support on this repo.

**Comment by soulseekah** [comment]
Why was this closed? This is a valid bug. There's a good PR associated with it.

**Comment by rmccue** [comment]
Apologies, was too quick with my closing of issues.
