### ISSUE TITLE
Globally set option to trust custom certificate

### ISSUE THREAD

**Issue by pimterry** [rmccue/Requests#342]
I'd like to use Requests through an intercepting proxy, which requires me to trust the proxy's CA certificate.

I can do this by explicitly passing the certificate to `verify`:

```php
$response = Requests::get($url, array(), array('verify' => $path_to_certificate));
```

I don't want to have to add that option to every single HTTP request everywhere in my codebase though.

Is there a way to globally configure options, to allow this? Even better would be an environment variable or php.ini setting to do so.

For curl & openssl in general for example there's `curl.cainfo=<path_to_certificate>` and `openssl.cafile=<path_to_certificate>`. I've tested using those for other clients (curl, guzzle, etc), and that works out of the box, but it doesn't help with Requests presumably due to the bundled CA certificates, and I can't see an equivalent alternative solution.

In a similar vein, I'd also be interested in a way to globally set the proxy configuration, as a solution to #218.

**Comment by rmccue** [comment]
Similar to https://github.com/rmccue/Requests/issues/218#issuecomment-234299405 this isn't Requests' responsibility. It is a standalone library, which intentionally doesn't use any global configuration; it's up to the library's user to provide this.
