### ISSUE TITLE
Handling large files

### ISSUE THREAD

**Issue by jdescelliers** [rmccue/Requests#344]
Hi,

I'm having trouble downloading large files since Requests is limited to the amount of memory set in php.ini, this is problematic because : 
- it's not easily configurable or documented,
- does not throw any exception, hence only PHP logs provide this information.

Any clean workaround to solve this?

**Comment by rmccue** [comment]
If you use the `filename` option, this will stream the body directly to a file in 1160 byte chunks (`Requests::BUFFER_SIZE`).
