### ISSUE TITLE
Trying to access array offset on value of type null when a domain value is null/false

### ISSUE THREAD

**Issue by aaronjorbin** [rmccue/Requests#369]
PHP 7.4 introduces a "Trying to access array offset on value of type ..." warning for accessing null/bool/int/float/resource (everything but array, string and object) as if it were an array.

The cookie attribute normalization assumes that the value in the case of domain is accessible via array offset, but possible for the attribute to be either null or false and this causes a warning.

**Comment by jrfnl** [comment]
Tested and confirmed.
