### ISSUE TITLE
Cookie jar handling with POST queries is not working

### ISSUE THREAD

**Issue by mouchh** [rmccue/Requests#373]
Hi guys,

I was discovering this library (thanks for your effort building a convenient HTTP handler for PHP) and I'm currently stuck while trying to send a POST query with a previous cookiejar.

Here is the code that is not working
```
$request1 = Requests::get('http://query1.com');
$cookiejar = $request1->cookies;
$request2 = Requests::post('http://query2.com', array(), array('cookies' => $cookiejar));

print_r($request2);
```

While debugging on `$request2`, I noticed no cookie were sent. When I switch the request type to GET I can see the cookies from the cookiejar... unfortunatly the server is denying my query due to a wrong type.

**Comment by mouchh** [comment]
Oh and by the way, I managed to find a workaround to get this working with POST. It is not as efficient as the cookiejar handling could be but its working :)

See my code:

```
$request1 = Requests::get('http://query1.com');
$cookies = '';
foreach ($request1->cookies->getIterator() as $cookie) $cookies .= $cookie->formatForHeader().';';
$cookies = substr_replace($cookies ,'', -1);

$request2= Requests::post('http://query2.com', array('Cookie' => $cookies));
```

**Comment by rmccue** [comment]
You appear to be passing the wrong parameters to `Requests::post()`. Note that the signature is different to `::get()`; `::post()` also takes a `$data` parameter.

This should work:

```php
$request2 = Requests::post('http://query2.com', array(), array(), array('cookies' => $cookiejar));
```
