### ISSUE TITLE
cUrl Error 60 - SSL on local development

### ISSUE THREAD

**Issue by maicol07** [rmccue/Requests#382]
Hi,
Requests isn't going to work if you are sending a request to your local webserver (for example XAMPP).
Here is the error:
```
Fatal error: Uncaught Requests_Exception: cURL error 60: SSL certificate problem: self signed certificate in certificate chain
```
And this is the code (I've also tried to set curl options before send but it doesn't work):
```
$hooks = new Requests_Hooks();
$hooks->register('curl.before_send', function ($fp) {
    curl_setopt($fp, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($fp, CURLOPT_SSL_VERIFYPEER, false);
}, 1);
$options = ['hooks' => $hooks];
$req = Requests::request($this->url . $path, $headers, $data, $method, $options);
return json_decode($req->body, true);
```

**Comment by maicol07** [comment]
Solved with the verify option

**Comment by thiagodp** [comment]
@maicol07 Which verify option?

**Comment by maicol07** [comment]
> @maicol07 Which verify option?

This one with setopt: https://www.php.net/manual/en/curl.constants.php#constant.curlopt-ssl-verifypeer
