### ISSUE TITLE
Post with Auth and Data

### ISSUE THREAD

**Issue by premudeshi** [rmccue/Requests#418]
Hello,

I get an 500 error every time I attempt to make a POST request with basic auth and data.

```
$headers = array('Accept' => 'application/json');
$options = array('auth' => array('username', 'pass'), 'data' => array('val1' => $val1, 'val2' => $val2));
$request = Requests::POST('https://localhost:5000/getRq', $headers, $options);
var_dump($request->status_code);
```
I know its got something to do with my code as everything else seems to work.

Thanks.

**Comment by premudeshi** [comment]
Being the joke I am, I just re-read the docs and realized there is a different parameter for data. 
This code worked for me.
```
$headers = array('Accept' => 'application/json');
$options = array('auth' => array('username', 'pass'));
$data = array('val1' => $val1, 'val2' => $val2);
$request = Requests::POST('https://localhost:5000/getRq', $headers, $data,$options);
var_dump($request->status_code);
```

**Comment by jrfnl** [comment]
Glad to hear you figured it out. Thanks for leaving a note with your solution as well in case others have the same question!
