### ISSUE TITLE
Handling timeouts?

### ISSUE THREAD

**Issue by cviebrock** [rmccue/Requests#42]
The docs says that one of Request's features is "Connection Timeouts", but I don't see anything in the docs about that.

Any example code on how to, say, do a get request that gives up after 5 seconds?

Thanks!

**Comment by foundryspatial-duncan** [comment]
Where in the docs does it say what you can put in the options array?

**Comment by ozh** [comment]
@foundryspatial-duncan at various places in the docs https://github.com/rmccue/Requests/blob/master/docs/usage.md

**Comment by foundryspatial-duncan** [comment]
The options array isn't mentioned on that page, but it would be helpful to at least put a link in there!
