### ISSUE TITLE
GET request query strings in $data paramater

### ISSUE THREAD

**Issue by sheedy** [rmccue/Requests#46]
First off, great library. It's really simple and helping me a lot so far.
I first set up a POST request and it worked as expected but got tripped up on GET requests.

On line 281 of `Requests.php`, `$data` is defined as:

```
@param array $data Data to send either as a query string for GET/HEAD requests, or in the body for POST requests
```

Based on this, one would expect the `get` function on line 193 of `Requests.php` to take $data as an input parameter but it doesn't.

```
public static function get($url, $headers = array(), $options = array()) {
    return self::request($url, $headers, null, self::GET, $options);
}
```

In fact it sets what the `request` function on line 286 expects as data to `null`.

If I use the following code:

```
$request = Requests::get($url . '?' . $query, $headers, $options);
```

or if I just include my `$query` in my `$url` variable then this works as expected. Is this how GET requests are supposed to be handled?

Wouldn't it make more sense to use `$data` the same way as you have for POST requests? Like so:

```
public static function get($url, $headers = array(), $data = array(), $options = array()) {
    return self::request($url, $headers, $data, self::GET, $options);
}
```

Then set up the request like the POST request in terms of parameters, placing the query inside the `$data` variable:

```
$request = Requests::get($url, $headers, $data, $options);
```

Am I missing something for how GET requests are handled? If so is there an example that includes the query string/data?

Thanks

**Comment by sudheesh001** [comment]
@rmccue Can this be documented in the API, there's no clear documentation as to how we can pass parameters in the GET request. So i think it's best to mention in the documentation that the GET request with parameters should be made into a string and you can use `Requests::request()` and pass the type.

Thanks for the great tool, we're using it at `loklak/loklak-php`
