### ISSUE TITLE
Task: automate updating the certificates bundle

### ISSUE THREAD

**Issue by jrfnl** [rmccue/Requests#635]
Thoughts:
* Use GH Actions with a daily cron schedule
* Check for changes to this page and/or RSS feed if available: https://curl.se/docs/caextract.html
* Use similar logic as used in the website update workflow to auto-generate a PR when a new bundle has been published.

**Comment by wojsmol** [comment]
We can simply wget https://curl.se/ca/cacert.pem and create PR if changes are detected.

**Comment by jrfnl** [comment]
FYI: I have this ready and waiting for a new certificate bundle to be published, so I can actually test that the workflow works as expected ;-)

**Comment by jrfnl** [comment]
Just saw that a new certificates bundle has been published on https://curl.se/docs/caextract.html, so I can now (finally) pull the new workflow. ~~If all goes well, a separate PR will automatically be opened with the certificate update.~~
**_Actually, for a PR which updates the workflow or the bundles, a new commit should be added to the open PR (if all goes well)._**

See: https://github.com/WordPress/Requests/pull/669
