### ISSUE TITLE
Uncaught exceptions ?

### ISSUE THREAD

**Issue by ozh** [rmccue/Requests#66]
Hi there

I'm currently [playing with Requests](https://github.com/ozh/YOURLS/tree/http-lib) and see if I can use it in YOURLS. I'm testing it under various cases and found one that doesn't work too well : when the transport is fsockopen and there's no SSL support, you end up with a fatal error if trying to perform a request on an `https://` URL : 

```
( ! ) Fatal error: Uncaught exception 'Requests_Exception' with message 'Unable to find the socket transport "ssl" - did you forget to enable it when you configured PHP?' in blah\Requests\Transport\fsockopen.php on line 97
( ! ) Requests_Exception: Unable to find the socket transport "ssl" - did you forget to enable it when you configured PHP? in blah\Requests\Transport\fsockopen.php on line 97
```

Not sure I understand everything correctly but it seems to me that no exception is caught, ever, hence whenever you're throwing a new one, it will die with a fatal error?

**Comment by fpilee** [comment]
interesting but there should be at least a throws in phpdoc so phpstorm warn about that
