### ISSUE TITLE
Relation to WordPress core

### ISSUE THREAD

**Issue by szepeviktor** [rmccue/Requests#764]
1. How do I find what Requests version is included in a certain WP release?
2. May I use Requests v1/v2 with WordPress core?

Thank you.

**Comment by szepeviktor** [comment]
> How do I find what Requests version is included in a certain WP release?

In `wp-includes/class-requests.php` `Requests::VERSION` shows the current version.

For example WP v6.0.1 contains Request v1.8.1

**Comment by szepeviktor** [comment]
> May I use Requests v1/v2 with WordPress core?

Yes.

In `wp-includes/class-wp-http.php`

```php
if ( ! class_exists( 'Requests' ) ) {
    require ABSPATH . WPINC . '/class-requests.php';
```

**Comment by jrfnl** [comment]
Requests 1.x is currently included with WordPress. There is a ticket open to upgrade the version included with WordPress to Requests 2.x: https://core.trac.wordpress.org/ticket/54504

Other than that, not sure what information you are looking for ? Can this ticket be closed ?

**Comment by szepeviktor** [comment]
Yes.
