### ISSUE TITLE
Encourage help with documentation

### ISSUE THREAD

**Issue by schlessera** [rmccue/Requests#789]
## Is your feature request related to a problem?
Documentation can always be improved, and no one is immune to typos and bad grammar.

## Describe the solution you'd like
We should explicitly encourage users of the Requests library to help with making the documentation the best it can be. Instead of only having a generic link to GitHub at the top, each page of the documentation should include a link right after the actual content of the page that invites corrections, something along the lines of:
```
Is something missing or did you find something to be wrong? Please <create an issue here>.
```

**Comment by jrfnl** [comment]
Task:
- [x] Create a documentation issue template
