### ISSUE TITLE
Not compatible with PHP 8.1

### ISSUE THREAD

**Issue by daveherman71** [rmccue/Requests#792]
A number of classes in the Requests package throw deprecation notices and are therefore not compatible with PHP 8.1, namely:

Requests/Cookie/Jar.php
Requests/Utility/CaseInsensitiveDictionary.php

You need to modify the classes and add the #[\ReturnTypeWillChange] attribute or otherwise implicitly set the return type of each of the methods that are affected.

The following article sheds light on how to address this problem:

> [https://roots.io/wordpress-php-8-1-support-not-found/#notices-from-wp-cli](https://roots.io/wordpress-php-8-1-support-not-found/#notices-from-wp-cli)

**Comment by daveherman71** [comment]
Upgrade the Requests package to version 2.0.5 resolves this issue

**Comment by jrfnl** [comment]
Closing as invalid. This was solved with the version 2.0.0 release.
