### ISSUE TITLE
Missing use/FQCN for Stringable

### ISSUE THREAD

**Issue by kkmuffme** [rmccue/Requests#803]
## Summary

namespace WpOrg\Requests classes use global namespace Stringable object in phpdoc, but "use" statement is missing everywhere.
e.g. Session.php `__construct`

Please add the use statement or use FQCN \Stringable in phpdoc

## Tested against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of Requests.

https://core.trac.wordpress.org/ticket/58092

**Comment by jrfnl** [comment]
Closing as invalid.

The class names used in the docblocks are already fully qualified, so I honestly don't know what you are talking about.

Also: `use` statements have no effect on docblocks. PHP completely ignores the docblocks. It's only static analysers which may benefit from those `use` statements, but there is no technical benefit.
