### ISSUE TITLE
Release checklist for 2.0.7

### ISSUE THREAD

**Issue by schlessera** [rmccue/Requests#807]
PRs to cherrypick into the next 2.0.x release:

- [x] [GH Actions: bump peter-evans/create-pull-request from 4 to 5 (#804)](https://github.com/WordPress/Requests/pull/804)
- [x] [GH Actions/update website: update for new "create pull request" action runner version (#805)](https://github.com/WordPress/Requests/pull/805)

**Comment by jrfnl** [comment]
Backports done and action runs green. Closing as finished.
