### ISSUE TITLE
WP_Query support for "is null" and "is not null" comparison operators

### ISSUE THREAD

**Issue by lllopo** [rmccue/Requests#812]
## Is your feature request related to a problem?
Currently WP_Query can look for empty string values in posts, users and their meta, but can not check for NULL values. If you do something of the type :
```
[
    'key'     => 'some_key',
    'compare' => '!=',
    'value' => ''
]
```
This would look for empty string (negative lookup in the example) but will miss the NULL values. 

## Describe the solution you'd like
An compare operators 'IS NULL' and 'IS NOT NULL' can be added.

## Describe alternatives you've considered
Alternatively, the current '=' and '!=' compare operators can be extended, so if the 'value' parameter is empty, they can check both for empty string and NULL in the same time as these are basically the same thing - empty. Adding 'is null' and 'is not null' is more fine grained, though.

**Comment by jrfnl** [comment]
@lllopo This is the repo for the Requests library not for WordPress and your issue has nothing to do with the Requests package.

I suggest you open a ticket in the [WordPress issue management system](https://core.trac.wordpress.org/) (if it doesn't exist already).

**Comment by lllopo** [comment]
@jrfnl yes, my mistake. Don't know how it happened. Apologies for that.
