### ISSUE TITLE
Progress callback?

### ISSUE THREAD

**Issue by scribu** [rmccue/Requests#98]
I understand that the cURL transport supports a progress callback: http://stackoverflow.com/a/13958587/97998

1) Do you happen to know if other transports support similar functionality?
2) Does Requests expose this functionality in a generic way, or do I have to use the `curl.before_send` hook?

Related: #77

**Comment by Markcial** [comment]
:+1: 

curl supports progress too http://stackoverflow.com/a/13958587/294700 is not very documented but it works.

**Comment by subins2000** [comment]
Has the ```request.progress``` hook been added to Requests ?

**Comment by rmccue** [comment]
@subins2000 It has now! :) See #180.

**Comment by subins2000** [comment]
Good work :+1:
